import board.KalahaBoard

object StartGame {
  def main(args: Array[String]): Unit = {
    val test = new KalahaBoard()
    test.printBoard()
    println(test.makeMove(6, true))
    test.printBoard()
    println(test.makeMove(1, true))
    test.printBoard()
    println(test.makeMove(2, true))
    test.printBoard()
    println(test.makeMove(3, true))
    test.printBoard()
    println(test.makeMove(4, true))
    test.printBoard()
    println(test.makeMove(5, true))
    test.printBoard()
    println(test.makeMove(6, true))
    test.printBoard()
    println(test.makeMove(1, true))
    test.printBoard()
    println(test.makeMove(2, true))
    test.printBoard()
    println(test.makeMove(3, true))
    test.printBoard()
    println(test.makeMove(4, true))
    test.printBoard()
    println(test.makeMove(5, true))
    test.printBoard()
    println(test.makeMove(6, true))
    test.printBoard()
    println(test.makeMove(1, true))
    test.printBoard()
    println(test.makeMove(2, true))
    test.printBoard()
    println(test.makeMove(3, true))
    test.printBoard()
    println(test.makeMove(4, true))
    test.printBoard()
    println(test.makeMove(5, true))
    test.printBoard()
    println(test.checkIsGameFinished(true))
    println(test.makeMove(6, true))
    test.printBoard()
    println(test.checkIsGameFinished(true))
    println(test.getResults())
  }
}
