//
// Created by jakubszwedowicz on 05.12.22.
//

#ifndef LIST_8_GAMESESSIONSATE_HPP
#define LIST_8_GAMESESSIONSATE_HPP

enum class GameSessionSate
{
    GAME_NOT_STARTED,
    WAITING_FOR_LOCAL_PLAYER,
    WAITING_FOR_BOT_MOVE,
    WAITING_FOR_REMOTE_PLAYER,
    WAITING_FOR_SERVER_VALIDATION,
    GAME_FINISHED
};

#endif //LIST_8_GAMESESSIONSATE_HPP
