//
// Created by jakubszwedowicz on 05.12.22.
//

#ifndef LIST_8_PLAYERMOVESTATE_HPP
#define LIST_8_PLAYERMOVESTATE_HPP
enum class PlayerMoveState
{
    NOT_MADE_MOVE,
    TO_BE_VALIDATED_MOVE,
    LOCAL_VALIDATED_MOVE,
    REMOTE_VALIDATED_MOVE
};
#endif //LIST_8_PLAYERMOVESTATE_HPP
